import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import Logout from '@/components/Logout'

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="ru">

      <body className={roboto.className}>
        <Header />

        {
          !session && <Link href="/login">Войти в аккаунт</Link>
        }

        {
          !!session && <Logout />
        }

        <main>
          {children}
        </main>


      </body>
    </html>
  )
}
