import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: ['300', '400', '500', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">

      <body className={roboto.className}>
        <Header />

        <main>
          {children}
        </main>


      </body>
    </html>
  )
}
